#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will #be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci():
	a = 1
	b = 1
	total = 0
	s = 0
	while s <= 4000000 :
		s = a + b
		a = b 
		b = s
		if s%2 == 0 :
			total += s

	return total

print fibonacci()